"""Adicionando chave estrangeira

Revision ID: 0e52c09c0f91
Revises: 0d35432ac1bc
Create Date: 2023-08-13 20:41:43.901815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e52c09c0f91'
down_revision: Union[str, None] = '0d35432ac1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Produto', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Produto', 'Usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Produto', type_='foreignkey')
    op.drop_column('Produto', 'usuario_id')
    # ### end Alembic commands ###
