"""nova column tamanho

Revision ID: 8c83d3076a12
Revises: 820c51c7422f
Create Date: 2023-08-12 12:29:50.476727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c83d3076a12'
down_revision: Union[str, None] = '820c51c7422f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Produto', sa.Column('tamanho', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Produto', 'tamanho')
    # ### end Alembic commands ###
